-- Borrow organizations and borrowing restrictions.
-- Run this once in Supabase SQL Editor.

create table if not exists public.borrow_organizations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.borrow_restrictions (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('user', 'organization')),
  user_id uuid references auth.users(id) on delete cascade,
  org_name text,
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint borrow_restrictions_target_check check (
    (target_type = 'user' and user_id is not null and org_name is null)
    or (target_type = 'organization' and user_id is null and nullif(trim(org_name), '') is not null)
  )
);

alter table public.borrow_organizations enable row level security;
alter table public.borrow_restrictions enable row level security;

create or replace function public.is_admin_user()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "authenticated can read borrow organizations" on public.borrow_organizations;
create policy "authenticated can read borrow organizations"
on public.borrow_organizations for select to authenticated using (true);

drop policy if exists "authenticated can manage borrow organizations" on public.borrow_organizations;
create policy "authenticated can manage borrow organizations"
on public.borrow_organizations for all to authenticated
using (public.is_admin_user()) with check (public.is_admin_user());

drop policy if exists "authenticated can read borrow restrictions" on public.borrow_restrictions;
create policy "authenticated can read borrow restrictions"
on public.borrow_restrictions for select to authenticated
using (public.is_admin_user() or user_id = auth.uid() or target_type = 'organization');

drop policy if exists "authenticated can manage borrow restrictions" on public.borrow_restrictions;
create policy "authenticated can manage borrow restrictions"
on public.borrow_restrictions for all to authenticated
using (public.is_admin_user()) with check (public.is_admin_user());

insert into public.borrow_organizations (name)
values
  ('ฝ่ายวิชาการ'),
  ('ฝ่ายสวัสดิการและสิทธิประโยชน์'),
  ('ฝ่ายศิลปวัฒนธรรม'),
  ('ฝ่ายกีฬาและนันทนาการ'),
  ('ชุมนุมค่ายอาสาพัฒนาสังคมสงเคราะห์')
on conflict (name) do nothing;
