-- Per-user restrictions for booking and borrowing.
-- Run once in the Supabase SQL Editor.

create table if not exists public.user_service_restrictions (
  id bigint generated by default as identity primary key,
  service_type text not null check (service_type in ('booking', 'borrowing')),
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.user_service_restrictions enable row level security;

drop policy if exists "users can read own service restrictions" on public.user_service_restrictions;
create policy "users can read own service restrictions"
on public.user_service_restrictions for select to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can read service restrictions" on public.user_service_restrictions;
create policy "admins can read service restrictions"
on public.user_service_restrictions for select to authenticated
using (public.is_admin_user());

drop policy if exists "admins can manage service restrictions" on public.user_service_restrictions;
create policy "admins can manage service restrictions"
on public.user_service_restrictions for all to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());
